name: Build Docker Image and Push to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: acrfinalsude.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build . -t acrfinalsude.azurecr.io/azure-final:${{ github.sha }}
          docker push acrfinalsude.azurecr.io/azure-final:${{ github.sha }}

      - name: Deploy image to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: api-app-final
          images: acrfinalsude.azurecr.io/azure-final:${{ github.sha }}

      - name: Logout
        run: az logout
